### ISSUE TITLE
EtherateMT PACKET_MMAP Mode

### ISSUE THREAD

**Issue by Dauie** [jwbensley/EtherateMT#37]
Hey James. I'm in the process of writing a port scanner and I am trying to take advantage of a PACKET_TX_RING for the transmission process. I first started reading a post you made on StackOverflow where you mentioned: 

"When using PACKET_MMAP in Tx mode, only one frame can be put into each ring block (rather than multiple frames per ring block as with Rx mode)" <--- I can't find this stated in the documentation.

So I went ahead and started reading this repo, and I found this page: "EtherateMT PACKET_MMAP Mode", where the same constraint for the TX_RING is stated (only one frame per block), but then crossed out...
Now, let me explain why this is pertinent, and hopefully, you could shed some light into the dark corners of my understanding.

Currently, my ring is composed of one block of pagesize (4096 on my sys) segmented into 32 frames where each frame is equal to 128 bytes.

Issue 1: Every other cycle (i.e. a send and a receive) my sending is failing. I can log that my thread is filling a frame, but when sent send() is returning 0.

Issue 2: Let's say we are on our 4th cycle (4 sends and recv's), when finding a frame, I notice that I will skip 4 frames which are still in status 1 (TP_STATUS_SEND_REQUEST), even though I've witnessed these frames leave my machine via packet capture (wireshark). I went ahead and started casting the frame->tp_status as a volatile uint32, but their status remains the same on subsequent calls. I've seen some people mention a "consumer pointer" but I have not seen anything in documentation mentioning this. Should I be moving my TX_RING pointer forward past each frame that is used?

If you like you can take a look at my ring setup here:
https://github.com/Dauie/hermes/blob/master/src/thread.c (line 53)

and usage:
https://github.com/Dauie/hermes/blob/master/src/scan.c (line 184)

**Comment by Dauie** [comment]
Reading your code now. Closing this.

**Comment by Dauie** [comment]
Hmmm I increased my frame size to be == tp_block_sz and increased the block count, so I have one frame per block, but I'm still seeing the issue where the kernel fails to see the frames I've requested to send on every other call. Any input would be highly helpful. Thanks.

**Comment by Dauie** [comment]
<3

**Comment by Dauie** [comment]
I've found that If I completely fill up the TX ring and send, everything goes well. Or If I just make a TX ring composed of 1 block and 1 frame, it works fine.
This being said I could allocate a new ring buffer each time I enter my scan, but this sounds very expensive.
I want to be able to allocate my ring once, use it initially for small batches of packets, then when my program has ramped up I can utilize the entire ring, and as my program winds down it will require fewer frames on the ring. 
Still trying to figure out how to get to my "goal" setup(1 block, 32 frames) working.  
Do you know if it is possible? I'm reading through af_packet.c right now to try and figure out why it would not be possible. 
Thanks for all of the resources you have on your wiki. It's been very helpful.

**Comment by jwbensley** [comment]
Hi @Dauie,

Sorry for the mega late reply! I'm not an expert on using PACKET_MMAP and the Tx/Rx rings but I'll try to answer as best as I can:

>  I first started reading a post you made on StackOverflow where you mentioned:
> 
> "When using PACKET_MMAP in Tx mode, only one frame can be put into each ring block (rather than multiple frames per ring block as with Rx mode)" <--- I can't find this stated in the documentation.

Yes, back when I was writing EtherateMT RX_RINGs existed only, see this commit from Jan 2017 which introduced the TX ring in PACKET_MMAP version 3 to the Linux Kernel:

https://github.com/torvalds/linux/commit/7f953ab2ba46e8649537942c0a64668ca2ce5cc5#diff-81f235b603c5ae4c53d7fd607db6a55f

Prior to that commit `- Currently only RX_RING available` and that was just into the latest and greatest Kernel, it was a while before I had my hands on it, so I was stuck with “proper” rings for Rx but not for Tx.

> So I went ahead and started reading this repo, and I found this page: "EtherateMT PACKET_MMAP Mode", where the same constraint for the TX_RING is stated (only one frame per block), but then crossed out...

Yeah I need to update the Wiki but that commit above is why that text is crossed out, TX_RINGs were added to version 3 which were supposed to supposed varying sized packets/frames per block and ring (I never tested varying sizes).  
&nbsp;  
&nbsp;  
  
> Now, let me explain why this is pertinent, and hopefully, you could shed some light into the dark corners of my understanding.
> 
> Currently, my ring is composed of one block of pagesize (4096 on my sys) segmented into 32 frames where each frame is equal to 128 bytes.
> 
> Issue 1: Every other cycle (i.e. a send and a receive) my sending is failing. I can log that my thread is filling a frame, but when sent send() is returning 0.
> 
> Issue 2: Let's say we are on our 4th cycle (4 sends and recv's), when finding a frame, I notice that I will skip 4 frames which are still in status 1 (TP_STATUS_SEND_REQUEST), even though I've witnessed these frames leave my machine via packet capture (wireshark). I went ahead and started casting the frame->tp_status as a volatile uint32, but their status remains the same on subsequent calls. I've seen some people mention a "consumer pointer" but I have not seen anything in documentation mentioning this. Should I be moving my TX_RING pointer forward past each frame that is used?

I haven't read about or used a "consumer pointer" unless I know it by another name?! The documentation isn't great on this feature I would say. The best documentation I found is to read the Kernel source code. It was a bit of a pain to get EtherateMR working but reading the Kernel source was the only way I could get my code to work and it makes sense doing this in hindsight. I traced all the functions I used (or that were being subsequently called by my calls to `socket()`, `setsockopt()` and `send()` etc.) through the Kernel using SystemTap so that I could read the source code of those functions and work out why calls to `send()` or `setsockopt()` were failing or not acting as expected. It is tedious but it also taught me a lot so I recommend it.

Here is an example:
https://github.com/jwbensley/EtherateMT/wiki/Linux-Kernel-tracing-for-sendto()-using-AF_PACKET,-PACKET_MMAP-and-PACKET_FANOUT

Kernel source (when using `PF_PACKET` or `AF_PACKET` you end up in this file):
https://elixir.bootlin.com/linux/latest/source/net/packet/af_packet.c
&nbsp;  
&nbsp;  

> If you like you can take a look at my ring setup here:
> https://github.com/Dauie/hermes/blob/master/src/thread.c (line 53)
> 
> and usage:
> https://github.com/Dauie/hermes/blob/master/src/scan.c (line 184)
…
> I've found that If I completely fill up the TX ring and send, everything goes well. Or If I just make a TX ring composed of 1 block and 1 frame, it works fine.
> This being said I could allocate a new ring buffer each time I enter my scan, but this sounds very expensive.
> I want to be able to allocate my ring once, use it initially for small batches of packets, then when my program has ramped up I can utilize the entire ring, and as my program winds down it will require fewer frames on the ring.
> Still trying to figure out how to get to my "goal" setup(1 block, 32 frames) working.
> Do you know if it is possible? I'm reading through af_packet.c right now to try and figure out why it would not be possible.
> Thanks for all of the resources you have on your wiki. It's been very helpful.

This is strange. I was writing a fairly basic program in that it's just a load generator / sinker;  In Tx mode the app fills the ring with the junk data frames and sends them all to create as much load on the Rx device as possible. Equally the Rx device just receives the frames and does nothing to "sink" as much traffic as possible. I never tried to half fill a ring or use varying frame sizes.

I have a memory like a sieve I'm afraid so I can't remember exactly why but, I couldn't get the RX_RING to work in PACKET_MMAP/TPACKET v3 without using `poll()` as per this function:
https://github.com/jwbensley/EtherateMT/blob/master/tpacket_v3.c#L273

It would work in v2 without `poll()` but I re-wrote the v2 part to also use `poll()` to match the v3 code:
https://github.com/jwbensley/EtherateMT/blob/master/tpacket_v2.c#L227

The difference between these two methods might be helpful to you though. I can't remember all the details but they do poll differently due to the change in RX_RING structure, note the use of IOVECs for the v3 TX/RX_RING, I set them up but actually put one frame in each block when Tx’ing with both v2 and v3 RINGS:
https://github.com/jwbensley/EtherateMT/blob/master/tpacket_v3.c#L443

…Here I am blindly filling the TX buffer; I don't check that a block in the ring has `TP_STATUS_AVAILABLE`;
https://github.com/jwbensley/EtherateMT/blob/master/tpacket_v3.c#L482

One issue I do remember having is that I could send packets faster than they were being de-queued to the NIC. The packet path is roughly (if I can remember correctly): userland application writes data to TX_RING > Kernel copies packet from TX_RING into an skb > skb goes into an output queue for the `socket()` > the Kernel then looks up the egress NIC and hashes the packet into an egress NIC Tx queue > the packet is then copied into memory space that is accessible to the NIC via DMA > Kernel signals NIC to DMA the packet.

I needed to increase the `socket()` output queue size here so that I could dequeue the entire TX_RING in each `send()` otherwise the Kernel wouldn’t copy all packets from the ring and set them to `TP_STATUS_AVAILABLE`:
https://github.com/jwbensley/EtherateMT/blob/master/tpacket_v3.c#L405
https://github.com/jwbensley/EtherateMT/blob/master/sock_op.c#L82

...and increase the size of the NIC output queue on the CLI:
https://github.com/jwbensley/EtherateMT/wiki/FAQ-&-Troubleshooting

I hope that helps!

**Comment by Dauie** [comment]
Yes, it does help. I appreciate you taking the time to write all of this out. Mostly It reassures me that I'm not a complete idiot :P. Currently, I'm trying to set up a VM with kernel debug symbols so that I can connect GDB from my hosting machine and start stepping through the send() path and actually see what's happening. Following this guide: 

http://www.alexlambert.com/2017/12/18/kernel-debugging-for-newbies.html

Might be a good debugging option for you as well next time you're working with a kernel API.

Cheers!
